name       : libgtk-4
version    : 4.10.1
release    : 27
source     :
    - https://download.gnome.org/sources/gtk/4.10/gtk-4.10.1.tar.xz : e8fcac04bc7715b9da667c911a5ee8f262e200d1d6a50adf23645ca8cfcd0311
license    : LGPL-2.0-or-later
component  :
    - desktop.gtk
    - demos : desktop.gtk
    - icon-browser : desktop.gtk
summary    :
    - libgtk-4 contains the libraries used for creating graphical user interfaces and applications.
    - demos : Demonstrations of major GTK4 features.
    - icon-browser : Sample application to graphically search well known GTK4 icon names.
description:
    - libgtk-4 contains the libraries used for creating graphical user interfaces and applications.
    - demos : Demonstrations of major GTK4 features.
    - icon-browser : Sample application to graphically search well known GTK4 icon names.
patterns   :
    - demos :
        - /usr/bin/gtk4-demo*
        - /usr/bin/gtk4-node*
        - /usr/bin/gtk4-print*
        - /usr/bin/gtk4-widget*
        - /usr/share/applications/org.gtk.Demo4*
        - /usr/share/applications/org.gtk*.NodeEditor*
        - /usr/share/applications/org.gtk.PrintEditor4*
        - /usr/share/applications/org.gtk.WidgetFactory4*
        - /usr/share/glib-2.0/schemas/org.gtk.Demo4*
        - /usr/share/icons/hicolor/*/apps/org.gtk.Demo4*
        - /usr/share/icons/hicolor/*/apps/org.gtk*.NodeEditor*
        - /usr/share/icons/hicolor/*/apps/org.gtk.PrintEditor4*
        - /usr/share/icons/hicolor/*/apps/org.gtk.WidgetFactory4*
        - /usr/share/metainfo/org.gtk.Demo4*
        - /usr/share/metainfo/org.gtk*.NodeEditor*
        - /usr/share/metainfo/org.gtk.PrintEditor4*
        - /usr/share/metainfo/org.gtk.WidgetFactory4*
    - icon-browser :
        - /usr/bin/gtk4-icon-browser
        - /usr/share/applications/org.gtk.IconBrowser4*
        - /usr/share/icons/hicolor/*/apps/org.gtk.IconBrowser*
        - /usr/share/metainfo/org.gtk.IconBrowser4*
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(cloudproviders)
    - pkgconfig(colord)
    - pkgconfig(graphene-1.0)
    - pkgconfig(epoxy)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gstreamer-player-1.0)
    - pkgconfig(libavformat)
    - pkgconfig(libcrypt)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(pango)
    - pkgconfig(rest-0.7)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xi)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(vulkan)
    - cups-devel
    - python-gobject
    - sassc
    - vulkan-headers
rundeps    :
    - devel :
        - vulkan-headers
setup      : |
    %meson_configure \
        -Dbuild-tests=false \
        -Dcloudproviders="enabled" \
        -Dcolord="enabled" \
        -Dgtk_doc=false \
        -Dintrospection="enabled" \
        -Dman-pages=false \
        -Doptimization=3 \
        -Dvulkan="enabled" \
        -Dwayland-backend=false
build      : |
    %ninja_build
install    : |
    %ninja_install
